In [133]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder

In [134]:
df = pd.read_csv('Datasets/iris1.csv')

In [135]:
df.head()

Sepal_Length   Sepal_Width   Petal_Length   Petal_Width        Class
0           5.1           3.5            1.4           0.2  Iris-setosa
1           4.9           3.0            1.4           0.2  Iris-setosa
2           4.7           3.2            1.3           0.2  Iris-setosa
3           4.6           3.1            1.5           0.2  Iris-setosa
4           5.0           3.6            1.4           0.2  Iris-setosa

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Sepal_Length   150 non-null    float64
 1    Sepal_Width   150 non-null    float64
 2    Petal_Length  150 non-null    float64
 3    Petal_Width   150 non-null    float64
 4   Class          150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [150]:
df = df.rename(columns = {' Sepal_Width':'Sepal_Width', 
          ' Petal_Length':'Petal_Length',
           ' Petal_Width':'Petal_Width',
          })

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal_Length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   Class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 7.0+ KB


In [152]:
label_encoder = LabelEncoder()
categories = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width']
features = tuple(zip(
    label_encoder.fit_transform(df[categories[0]]), 
    label_encoder.fit_transform(df[categories[1]]),
    label_encoder.fit_transform(df[categories[2]]),
    label_encoder.fit_transform(df[categories[3]])
))

In [154]:
new_df = pd.DataFrame(features, columns = categories)

In [155]:
new_df.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0             8           14             4            1
1             6            9             4            1
2             4           11             3            1
3             3           10             5            1
4             7           15             4            1

In [156]:
y = label_encoder.fit_transform(df['Class'])

In [172]:
model = MultinomialNB(force_alpha=True)

In [173]:
from sklearn.model_selection import train_test_split

In [174]:
x_train, x_test, y_train, y_test = train_test_split(new_df, y)

In [175]:
model.fit(x_train, y_train)

MultinomialNB(force_alpha=True)

In [176]:
model.score(x_test, y_test)

0.8157894736842105

In [177]:
model.predict(new_df)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1,
       1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2,
       1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2])

In [162]:
df = df.drop(columns = ['Class'])

In [185]:
x_train, x_test, y_train, y_test = train_test_split(df, y)

In [186]:
model.fit(x_train, y_train)

MultinomialNB(force_alpha=True)

In [187]:
model.score(x_test, y_test)

0.9473684210526315

In [183]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [213]:
cat = label_encoder.classes_
cat

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [220]:
res = np.where(cat=='Iris-versicolor')
res[0][0]

1

In [189]:
from sklearn.datasets import load_iris
iris = load_iris()
 
# store the feature matrix (X) and response vector (y)
X = iris.data
y = iris.target


In [203]:
X[0], df.loc[0]

(array([5.1, 3.5, 1.4, 0.2]),
 Sepal_Length    5.1
 Sepal_Width     3.5
 Petal_Length    1.4
 Petal_Width     0.2
 Name: 0, dtype: float64)

In [209]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)
 
# training the model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
 
# making predictions on the testing set
y_pred = gnb.predict(X_test)
 
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 95.0
